title: "WEBSITE"
author: Aiden Garrett
email: agarr2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
Welcome to Aiden's Website

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
